spring.application.name=javaprac
spring.datasource.url=jdbc:postgresql://localhost:5432/javaprac
spring.datasource.username=postgres
spring.datasource.password=0438

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
app.admin.email=admin@example.com
app.admin.password=admin